services:
  - type: web
    name: attendance-system
    env: python
    buildCommand: |
      echo "Current directory: $(pwd)"
      echo "Listing files:"
      ls -la
      # Using prebuilt wheels for dlib, no need for system dependencies
      if [ -f "requirements.txt" ]; then
        pip install -r requirements.txt
      elif [ -f "./requirements.txt" ]; then
        pip install -r ./requirements.txt
      elif [ -f "$PWD/requirements.txt" ]; then
        pip install -r $PWD/requirements.txt
      else
        echo "Installing packages directly"
        pip install Flask==2.0.1 Werkzeug==2.0.1 Jinja2==3.0.1 click==8.0.1 itsdangerous==2.0.1 MarkupSafe==2.0.1 gunicorn==20.1.0 Flask-SQLAlchemy==2.5.1 SQLAlchemy==1.4.23 face-recognition==1.3.0 opencv-python==4.9.0.80 dlib-binary==19.24.2
      fi
    startCommand: gunicorn app:app
    rootDirectory: ./
    repo:
      url: https://github.com/devilbeast05/attendence-system-
      branch: master
      referenceType: commit
      referenceValue: ba51f8fd24c91a74865075138ff07cf7e682a17b