services:
  - type: web
    name: attendance-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    repo:
      url: https://github.com/devilbeast05/attendence-system-
      branch: master
      referenceType: branch
      referenceValue: master